### ISSUE TITLE
Relax Theia dependency version ranges

### ISSUE THREAD

**Issue by mcgordonite** [eclipse-theia/theia-cpp-extensions#106]
@theia/cpp version 1.0.0 set the dependency range for other theia dependencies to `"latest"`, e.g. https://github.com/eclipse-theia/theia-cpp-extensions/blob/v1.0.0/packages/cpp/package.json#L6.

This is problematic when trying to use it in an application not using the latest Theia version. For example, try running `yarn install` with this package.json:

```json
{
  "dependencies": {
    "@theia/core": "1.2.0",
    "@theia/cpp": "1.0.0"
  }
}
```

This pulls in two different versions of `@theia/core`, breaking the application.

Suggestion: we should relax the version range for Theia dependencies to something like `"^1.0.0"`.

**Comment by vince-fugnitto** [comment]
@mcgordonite thank you for the issue, please prepare a pull-request if the fix is important for your use-case.
Please note that `@theia/cpp` will be deprecated (since it makes use of deprecated extensions such as `@theia/languages`), and vscode extensions should be used alternatively to provide C/C++ language support:

For our docker images (`theia-cpp`) we have been using `vscode-clangd` which is officially maintained by the LLVM community: https://github.com/theia-ide/theia-apps/blob/master/theia-cpp-docker/latest.package.json#L122

https://github.com/clangd/vscode-clangd

**Comment by mcgordonite** [comment]
@vince-fugnitto thanks for your help. We will investigate moving to `vscode-clangd`. For now though, I've created a PR that also bumps the version for release: https://github.com/eclipse-theia/theia-cpp-extensions/pull/107

After the release, should we revert the Theia dependencies to `"next"`?

**Comment by vince-fugnitto** [comment]
@mcgordonite thanks, unfortunately I don't believe it is possible for you to create a release due to permissions, and not having the proper `npm token` to publish releases to `npm`. It will likely need to be done by a committer with the right permissions and due to priorities and the fact that the extension is now deprecated it may take some time to complete.

cc @marcdumais-work

**Comment by marcdumais-work** [comment]
Hi @mcgordonite,

I think the problem you report is generic and not specific to @theia/cpp. Unfortunately I do not think your PR would help much, generally.

Each Theia framework extension has dependencies towards `"own version or later"` of other framework extensions (@theia/cpp goes a bit further using `latest` because it's in its own repo and we did not want to be forced to publish new versions along the other extensions unless we had new content or it needed to be updated to remain compatible with the rest). So if you try to include any `@theia` extension that's not latest, that has dependencies towards other `@theia` extension(s), I think you'll end-up with a similar result, unless your app's `yarn.lock` is crafted carefully to pin everything down.

e.g. you'd get into the same type of situation with:
```package.json
  "dependencies": {
    "@theia/core": "1.3.0",
    "@theia/terminal": "1.3.0",
    "@theia/cli": "1.3.0"
  }
```

```
$ yarn why @theia/core
yarn why v1.22.4
[1/4] Why do we have the module "@theia/core"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@theia/core@1.3.0"
info Has been hoisted to "@theia/core"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "9.36MB"
info Disk size with unique dependencies: "26.67MB"
info Disk size with transitive dependencies: "56.93MB"
info Number of shared dependencies: 127
=> Found "@theia/terminal#@theia/core@1.4.0"
info This module exists because "@theia#terminal" depends on it.
info Disk size without dependencies: "9.38MB"
info Disk size with unique dependencies: "26.68MB"
info Disk size with transitive dependencies: "56.94MB"
info Number of shared dependencies: 127
=> Found "@theia/filesystem#@theia/core@1.4.0"
info This module exists because "@theia#terminal#@theia#filesystem" depends on it.
info Disk size without dependencies: "9.38MB"
info Disk size with unique dependencies: "26.68MB"
info Disk size with transitive dependencies: "56.94MB"
info Number of shared dependencies: 127
=> Found "@theia/editor#@theia/core@1.4.0"
info This module exists because "@theia#terminal#@theia#editor" depends on it.
info Disk size without dependencies: "9.38MB"
info Disk size with unique dependencies: "26.68MB"
info Disk size with transitive dependencies: "56.94MB"
info Number of shared dependencies: 127
=> Found "@theia/process#@theia/core@1.4.0"
info This module exists because "@theia#terminal#@theia#process" depends on it.
info Disk size without dependencies: "9.38MB"
info Disk size with unique dependencies: "26.68MB"
info Disk size with transitive dependencies: "56.94MB"
info Number of shared dependencies: 127
=> Found "@theia/workspace#@theia/core@1.4.0"
info This module exists because "@theia#terminal#@theia#workspace" depends on it.
info Disk size without dependencies: "9.38MB"
info Disk size with unique dependencies: "26.68MB"
info Disk size with transitive dependencies: "56.94MB"
info Number of shared dependencies: 127
=> Found "@theia/variable-resolver#@theia/core@1.4.0"
info This module exists because "@theia#terminal#@theia#editor#@theia#variable-resolver" depends on it.
info Disk size without dependencies: "9.38MB"
info Disk size with unique dependencies: "26.68MB"
info Disk size with transitive dependencies: "56.94MB"
info Number of shared dependencies: 127
=> Found "@theia/languages#@theia/core@1.4.0"
info This module exists because "@theia#terminal#@theia#editor#@theia#languages" depends on it.
info Disk size without dependencies: "9.38MB"
info Disk size with unique dependencies: "26.68MB"
info Disk size with transitive dependencies: "56.94MB"
info Number of shared dependencies: 127
Done in 2.23s.

```

The only work-around that I know is to use a `resolutions` block to pin-down each extensions to one specific version you want. They do not need to be the same version all of them, but if not there are risks of incompatibility. 

e.g. something like:

```package.json
"resolutions": {
    "@theia/cpp": "1.0.0",
    "@theia/callhierarchy": "1.3.0",
    "@theia/console": "1.3.0",
    "@theia/core": "1.3.0",
    "@theia/debug": "1.3.0",
    "@theia/editor": "1.3.0",
    "@theia/editor-preview": "1.3.0",
    "@theia/file-search": "1.3.0",
    "@theia/filesystem": "1.3.0",
    "@theia/getting-started": "1.3.0",
    "@theia/git": "1.3.0",
    "@theia/keymaps": "1.3.0",
    "@theia/languages": "1.3.0",
    "@theia/markers": "1.3.0",
    "@theia/messages": "1.3.0",
    "@theia/metrics": "1.3.0",
    "@theia/mini-browser": "1.3.0",
    "@theia/monaco": "1.3.0",
    "@theia/navigator": "1.3.0",
    "@theia/outline-view": "1.3.0",
    "@theia/output": "1.3.0",
    "@theia/plugin-dev": "1.3.0",
    "@theia/plugin-ext": "1.3.0",
    "@theia/plugin-ext-vscode": "1.3.0",
    "@theia/plugin-metrics": "1.3.0",
    "@theia/preferences": "1.3.0",
    "@theia/preview": "1.3.0",
    "@theia/process": "1.3.0",
    "@theia/scm": "1.3.0",
    "@theia/scm-extra": "1.3.0",
    "@theia/search-in-workspace": "1.3.0",
    "@theia/task": "1.3.0",
    "@theia/terminal": "1.3.0",
    "@theia/typehierarchy": "1.3.0",
    "@theia/userstorage": "1.3.0",
    "@theia/variable-resolver": "1.3.0",
    "@theia/vsx-registry": "1.3.0",
    "@theia/workspace": "1.3.0",
    "@theia/cli": "1.3.0",
    "@theia/application-manager": "1.3.0"
  },
```

```
$ yarn why @theia/core
yarn why v1.22.4
[1/4] Why do we have the module "@theia/core"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@theia/core@1.3.0"
info Has been hoisted to "@theia/core"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "@theia#terminal#@theia#core"
   - Hoisted from "@theia#terminal#@theia#process#@theia#core"
   - Hoisted from "@theia#terminal#@theia#workspace#@theia#core"
   - Hoisted from "@theia#terminal#@theia#filesystem#@theia#core"
   - Hoisted from "@theia#terminal#@theia#editor#@theia#core"
   - Hoisted from "@theia#terminal#@theia#editor#@theia#languages#@theia#core"
   - Hoisted from "@theia#terminal#@theia#editor#@theia#variable-resolver#@theia#core"
info Disk size without dependencies: "9.36MB"
info Disk size with unique dependencies: "26.67MB"
info Disk size with transitive dependencies: "56.93MB"
info Number of shared dependencies: 127
Done in 0.83s.
```

**Comment by mcgordonite** [comment]
Hi @marcdumais-work, thanks for the response. You're correct, this is a problem in the main Theia repo too.

We haven't noticed this before because we were previously on Theia < 1.0.0. For versions less than 1, caret dependency ranges (e.g. `"^0.15.0"`) only pull in versions that differ in the patch (e.g. `"0.15.1"`). With versions >1 caret ranges apply to the minor version instead, so it is a lot more of a problem.

Thanks for the `"resolutions"` idea, I think that's the only way to guarantee only one copy of each theia extension in the dependency tree. It's just a pain to maintain a separate list of every theia package.
